//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Departement
    {
        public Departement()
        {
            this.todolists = new HashSet<todolist>();
        }
    
        public int id { get; set; }
        public string dname { get; set; }
    
        public virtual ICollection<todolist> todolists { get; set; }
    }
}
