//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TDL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class todolist
    {
        public int tid { get; set; }
        public string title { get; set; }
        public string description { get; set; }
        public Nullable<bool> IsDeleted { get; set; }
        public Nullable<int> id { get; set; }
    
        public virtual Departement Departement { get; set; }
    }
}
